export const seedData = {
  version: 6,
  profile: {
    firm: "Harcourt & Byrne — Demo Firm",
    user: "Niamh Kelly",
    initials: "NK",
    role: "Partner",
  },
  metrics: [
    { id: "active", label: "Active matters", value: "128", delta: "+6 this month", tone: "navy", icon: "briefcase" },
    { id: "deadlines", label: "Deadlines this week", value: "7", delta: "2 need review", tone: "amber", icon: "calendar" },
    { id: "wip", label: "Work in progress", value: "€188,260", delta: "86% of monthly plan", tone: "teal", icon: "clock" },
    { id: "client-funds", label: "Client funds ledger", value: "€1,246,030", delta: "€2,500 statement difference", tone: "amber", icon: "wallet" },
  ],
  matters: [
    {
      id: "MAT-2026-0142",
      title: "O'Rourke — 14 Alder Quay purchase",
      client: "Sample Client O'Rourke",
      type: "Conveyancing",
      stage: "Pre-contract",
      owner: "Niamh Kelly",
      ownerInitials: "NK",
      status: "Attention",
      risk: "High",
      nextDeadline: "Today, 16:00",
      updated: "12 min ago",
      value: "€485,000",
      progress: 46,
      code: "CONV-ALDER-24",
    },
    {
      id: "MAT-2026-0138",
      title: "Northstar Foods Ltd — share acquisition",
      client: "Northstar Foods Ltd (Demo)",
      type: "Corporate",
      stage: "Due diligence",
      owner: "Fionn Daly",
      ownerInitials: "FD",
      status: "On track",
      risk: "Medium",
      nextDeadline: "26 Aug, 10:00",
      updated: "31 min ago",
      value: "€2.4m",
      progress: 63,
      code: "CORP-NSF-06",
    },
    {
      id: "MAT-2026-0127",
      title: "Byrne estate administration",
      client: "Sample Estate of P. Byrne",
      type: "Probate",
      stage: "Revenue review",
      owner: "Eimear Walsh",
      ownerInitials: "EW",
      status: "Waiting",
      risk: "Low",
      nextDeadline: "28 Aug, 17:00",
      updated: "1 hr ago",
      value: "€760,000",
      progress: 72,
      code: "PROB-PB-19",
    },
    {
      id: "MAT-2026-0119",
      title: "Keane v Demo Logistics Ltd",
      client: "Sample Client Keane",
      type: "Litigation",
      stage: "Discovery",
      owner: "Ciarán Murphy",
      ownerInitials: "CM",
      status: "On track",
      risk: "Medium",
      nextDeadline: "01 Sep, 12:00",
      updated: "Yesterday",
      value: "€96,000 claim",
      progress: 58,
      code: "LIT-KDL-31",
    },
    {
      id: "MAT-2026-0106",
      title: "Sample Client Gallagher — employment advice",
      client: "Sample Client Gallagher",
      type: "Employment",
      stage: "Advice issued",
      owner: "Fionn Daly",
      ownerInitials: "FD",
      status: "Waiting",
      risk: "Low",
      nextDeadline: "04 Sep, 09:00",
      updated: "Yesterday",
      value: "€12,500 exposure",
      progress: 81,
      code: "EMP-SG-12",
    },
  ],
  priorities: [
    {
      id: "PRI-1",
      kind: "Statutory deadline",
      title: "Reply to Requisitions on Title is due today",
      detail: "MAT-2026-0142 · AI found two unanswered items in the latest client email.",
      tone: "danger",
      action: "Review matter",
      matterId: "MAT-2026-0142",
    },
    {
      id: "PRI-2",
      kind: "Accounts control",
      title: "Client-to-office transfer needs a Bill of Costs reference",
      detail: "€4,860 remains blocked until the written fee notification is linked.",
      tone: "warning",
      action: "Open accounts",
    },
    {
      id: "PRI-3",
      kind: "Intake cross-check",
      title: "Three new instructions contain conflicting case codes",
      detail: "The same client reference appears across email and CSV with different matter IDs.",
      tone: "info",
      action: "Review intake",
    },
  ],
  tasks: [
    { id: "TSK-201", title: "Review Requisitions on Title responses", matter: "MAT-2026-0142", due: "10:30", owner: "You", status: "In progress", priority: "High" },
    { id: "TSK-202", title: "Approve Northstar diligence summary", matter: "MAT-2026-0138", due: "12:00", owner: "You", status: "Ready", priority: "Medium" },
    { id: "TSK-203", title: "Call executor about outstanding valuation", matter: "MAT-2026-0127", due: "14:30", owner: "Eimear", status: "Not started", priority: "Medium" },
    { id: "TSK-204", title: "Finalise discovery index", matter: "MAT-2026-0119", due: "16:45", owner: "Ciarán", status: "Not started", priority: "Low" },
  ],
  activity: [
    { id: "ACT-1", icon: "sparkles", title: "AI matter brief reviewed", detail: "Northstar Foods Ltd — 4 sources cited", time: "09:42", actor: "Niamh Kelly" },
    { id: "ACT-2", icon: "file", title: "Document filed", detail: "Signed engagement letter · MAT-2026-0142", time: "09:28", actor: "Fionn Daly" },
    { id: "ACT-3", icon: "clock", title: "Time entry posted", detail: "0.8h · Keane v Demo Logistics Ltd", time: "09:14", actor: "Ciarán Murphy" },
    { id: "ACT-4", icon: "mail", title: "Client portal update opened", detail: "Sample Estate of P. Byrne", time: "08:51", actor: "Client portal" },
  ],
  notifications: [
    { id: "NOT-1", title: "Deadline moved forward", detail: "MAT-2026-0142 is now due today at 16:00", unread: true },
    { id: "NOT-2", title: "Draft bill ready", detail: "Northstar Foods Ltd · €8,420", unread: true },
    { id: "NOT-3", title: "Portal file received", detail: "Proof of address added to MAT-2026-0138", unread: false },
  ],
  intake: [
    {
      id: "INT-0841",
      source: "Client email + CSV",
      sender: "Sample Client O'Rourke",
      subject: "Alder Quay — replies and updated instructions",
      received: "09:37",
      status: "Review needed",
      confidence: 82,
      proposedMatter: "MAT-2026-0142",
      issue: "Two external case codes differ and a €5,000 payment is only mentioned in email.",
      codes: ["CONV-ALDER-24", "AQ-024-A", "CLIENT-7719"],
      extracted: [
        ["Client", "Sample Client O'Rourke", "Email signature"],
        ["Property", "14 Alder Quay, Dublin 2", "CSV row 18"],
        ["Purchase price", "€485,000", "Contract draft p.2"],
        ["Possible payment", "€5,000", "Email, 23 Aug"],
      ],
    },
    {
      id: "INT-0840",
      source: "Outlook email",
      sender: "Northstar Foods Ltd (Demo)",
      subject: "Final disclosure bundle — tranche 2",
      received: "09:12",
      status: "Matched",
      confidence: 97,
      proposedMatter: "MAT-2026-0138",
      issue: "No conflicts found. Three attachments ready to file.",
      codes: ["CORP-NSF-06", "NSF-MA-2026"],
      extracted: [["Company", "Northstar Foods Ltd", "Email domain"], ["Document set", "Disclosure tranche 2", "Subject line"]],
    },
    {
      id: "INT-0839",
      source: "Client portal",
      sender: "Sample Estate of P. Byrne",
      subject: "Property valuation uploaded",
      received: "08:48",
      status: "Ready to file",
      confidence: 99,
      proposedMatter: "MAT-2026-0127",
      issue: "Single PDF matched by secure portal link.",
      codes: ["PROB-PB-19"],
      extracted: [["Asset", "Residential property", "Valuation p.1"], ["Valuation", "€420,000", "Valuation p.2"]],
    },
    {
      id: "INT-0838",
      source: "Shared drive",
      sender: "Unassigned import",
      subject: "Legacy case folder — 31 files",
      received: "Yesterday",
      status: "Manual review",
      confidence: 54,
      proposedMatter: "Unmatched",
      issue: "No reliable matter reference found. Contains mixed client names.",
      codes: ["LEGACY-009", "UNKNOWN-31"],
      extracted: [["Files", "31", "Folder scan"], ["Possible clients", "3", "Entity extraction"]],
    },
  ],
  documents: [
    {
      id: "DOC-101",
      matterId: "MAT-2026-0142",
      folder: "01 Property",
      name: "Contract for Sale — draft 3.pdf",
      type: "PDF",
      date: "23 Aug 2026",
      size: "2.8 MB",
      owner: "Niamh Kelly",
      status: "AI reviewed",
      pages: 24,
      summary: "Draft contract for the purchase of 14 Alder Quay. Closing date remains provisional and two title requisitions are unresolved.",
      extracted: [["Purchase price", "€485,000", "99%"], ["Closing date", "18 Sep 2026", "86%"], ["Folio", "DN123456F", "98%"], ["Vendor solicitor", "Demo Legal LLP", "93%"]],
      content: ["CONTRACT FOR SALE", "Property: 14 Alder Quay, Dublin 2", "Purchase Price: €485,000", "Proposed Closing: 18 September 2026", "Folio: DN123456F", "DRAFT — subject to replies to Requisitions on Title"],
    },
    {
      id: "DOC-102",
      matterId: "MAT-2026-0142",
      folder: "02 Correspondence",
      name: "Client instructions — 23 Aug.eml",
      type: "Email",
      date: "23 Aug 2026",
      size: "184 KB",
      owner: "Niamh Kelly",
      status: "Needs review",
      pages: 1,
      summary: "Client confirms survey receipt and refers to a €5,000 payment not present in the latest instruction CSV.",
      extracted: [["Possible payment", "€5,000", "92%"], ["Survey", "Received", "97%"], ["Authority to exchange", "Not found", "—"]],
      content: ["From: Sample Client O'Rourke", "Subject: Alder Quay update", "We received the survey and paid the additional €5,000 on Friday.", "Please let us know if anything else is needed before exchange."],
    },
    {
      id: "DOC-103",
      matterId: "MAT-2026-0142",
      folder: "03 Compliance",
      name: "AML identity check.pdf",
      type: "PDF",
      date: "18 Aug 2026",
      size: "640 KB",
      owner: "Fionn Daly",
      status: "Incomplete",
      pages: 3,
      summary: "Identity evidence is present. Proof of address is missing, so the Exchange stage remains blocked.",
      extracted: [["Identity evidence", "Verified", "100%"], ["Proof of address", "Missing", "100%"], ["Source of funds", "Pending review", "100%"]],
      content: ["AML / KYC REVIEW", "Identity document: received and checked", "Proof of address: MISSING", "Source of funds: evidence received — review pending", "Prototype workflow aid only"],
    },
    {
      id: "DOC-104",
      matterId: "MAT-2026-0142",
      folder: "04 Title",
      name: "Requisitions on Title — replies.docx",
      type: "Word",
      date: "24 Aug 2026",
      size: "96 KB",
      owner: "Niamh Kelly",
      status: "2 gaps found",
      pages: 11,
      summary: "Draft replies are complete except for items 14 and 22, both awaiting supporting evidence.",
      extracted: [["Answered", "24 of 26", "100%"], ["Open item", "14 — planning evidence", "96%"], ["Open item", "22 — service charge", "94%"]],
      content: ["REPLIES TO REQUISITIONS ON TITLE", "Matter: MAT-2026-0142", "Items answered: 24 / 26", "Item 14: Awaiting planning evidence", "Item 22: Awaiting service charge confirmation"],
    },
    { id: "DOC-105", matterId: "MAT-2026-0138", folder: "Due diligence", name: "Disclosure index — tranche 2.xlsx", type: "Excel", date: "24 Aug 2026", size: "420 KB", owner: "Fionn Daly", status: "Filed", pages: 6, summary: "Disclosure index for the second diligence tranche.", extracted: [["Items", "84", "99%"], ["Open questions", "7", "98%"]], content: ["NORTHSTAR FOODS LTD", "Disclosure index — tranche 2", "84 documents / 7 open questions"] },
    { id: "DOC-106", matterId: "MAT-2026-0127", folder: "Assets", name: "Residential valuation.pdf", type: "PDF", date: "24 Aug 2026", size: "1.1 MB", owner: "Eimear Walsh", status: "Filed", pages: 8, summary: "Independent residential property valuation.", extracted: [["Valuation", "€420,000", "99%"]], content: ["PROPERTY VALUATION", "Market value: €420,000", "Prepared for probate purposes"] },
  ],
  matterDetails: {
    "MAT-2026-0142": {
      overview: "Purchase of a leasehold apartment at 14 Alder Quay. The file is in pre-contract review with a proposed 18 September closing. AI has found two incomplete title replies and an unresolved payment discrepancy.",
      briefUpdated: "10:06 today",
      confidence: 91,
      facts: [
        { label: "Property", value: "14 Alder Quay, Dublin 2", source: "Contract p.2" },
        { label: "Purchase price", value: "€485,000", source: "Contract p.2" },
        { label: "Proposed closing", value: "18 Sep 2026", source: "Contract p.4" },
        { label: "Client account", value: "€48,500 held", source: "Ledger 24 Aug" },
      ],
      risks: [
        { tone: "danger", title: "Reply deadline today", detail: "Two Requisitions on Title remain unanswered. Solicitor verification required." },
        { tone: "warning", title: "Instruction discrepancy", detail: "A €5,000 payment appears in email but not in the latest client CSV." },
        { tone: "warning", title: "AML stage gate", detail: "Proof of address is missing and source-of-funds review is pending." },
      ],
      parties: [
        { role: "Purchaser", name: "Sample Client O'Rourke", meta: "Portal active" },
        { role: "Vendor", name: "Sample Vendor Holdings Ltd", meta: "Corporate" },
        { role: "Vendor solicitor", name: "Demo Legal LLP", meta: "Opposing solicitor" },
        { role: "Lender", name: "Example Bank plc", meta: "Loan offer received" },
      ],
      codes: ["CONV-ALDER-24", "AQ-024-A", "CLIENT-7719"],
      keyDates: [
        { date: "24 Aug", time: "16:00", title: "Replies due", status: "Critical", source: "Vendor email" },
        { date: "28 Aug", time: "12:00", title: "Client authority check", status: "Review", source: "Workflow template" },
        { date: "18 Sep", time: "10:00", title: "Proposed closing", status: "Provisional", source: "Contract draft" },
      ],
      workflow: {
        stages: ["Intake", "AML & funds", "Pre-contract", "Exchange", "Closing", "Registration"],
        current: 2,
        blockers: ["Proof of address is missing", "Source-of-funds evidence needs review", "Requisitions 14 and 22 are unanswered", "Written authority to exchange is missing"],
        checks: [
          { id: "WF-1", title: "Engagement letter signed", owner: "Fionn Daly", due: "Complete", done: true },
          { id: "WF-2", title: "Identity evidence verified", owner: "Fionn Daly", due: "Complete", done: true },
          { id: "WF-3", title: "Review proof of address", owner: "Niamh Kelly", due: "Today", done: false },
          { id: "WF-4", title: "Review source-of-funds and payment evidence", owner: "Niamh Kelly", due: "Today", done: false },
          { id: "WF-5", title: "Complete title replies 14 and 22", owner: "Niamh Kelly", due: "16:00", done: false },
          { id: "WF-6", title: "Obtain written authority to exchange", owner: "Client", due: "Before exchange", done: false },
        ],
      },
      communications: [
        { id: "MSG-1", side: "in", sender: "Sample Client O'Rourke", time: "23 Aug, 16:42", text: "We received the survey and paid the additional €5,000 on Friday. Please let us know what is still needed before exchange.", status: "Filed" },
        { id: "MSG-2", side: "out", sender: "Niamh Kelly", time: "23 Aug, 17:06", text: "Thank you. We are checking the updated figures and will send a short list of the remaining items tomorrow.", status: "Delivered" },
        { id: "MSG-3", side: "in", sender: "Sample Client O'Rourke", time: "Today, 08:51", text: "The address document should be available later today. Is the proposed closing date still realistic?", status: "Needs reply" },
      ],
      audit: [
        { time: "10:06", actor: "AI review · pending", action: "Matter brief refreshed", detail: "4 documents and 3 communications cited" },
        { time: "09:44", actor: "Niamh Kelly", action: "Deadline confirmed", detail: "Replies due 24 Aug at 16:00 · vendor email linked" },
        { time: "09:37", actor: "AI intake · pending", action: "Instruction discrepancy flagged", detail: "€5,000 payment mentioned in email only" },
        { time: "Yesterday", actor: "Fionn Daly", action: "AML review updated", detail: "Identity verified; proof of address remains missing" },
      ],
    },
  },
  workflowBoard: [
    { stage: "Intake", count: 14, matters: [{ title: "Byrne probate instruction", id: "MAT-2026-0127" }, { title: "Gallagher employment advice", id: "MAT-2026-0106" }, { title: "Alder Quay instruction batch", id: "MAT-2026-0142" }] },
    { stage: "Active work", count: 62, matters: [{ title: "Northstar due diligence", id: "MAT-2026-0138" }, { title: "Keane discovery", id: "MAT-2026-0119" }, { title: "Alder Quay pre-contract", id: "MAT-2026-0142" }] },
    { stage: "Client action", count: 29, matters: [{ title: "Alder Quay AML evidence", id: "MAT-2026-0142" }, { title: "Byrne executor valuation", id: "MAT-2026-0127" }, { title: "Gallagher response", id: "MAT-2026-0106" }] },
    { stage: "Closing", count: 23, matters: [{ title: "Alder Quay closing preparation", id: "MAT-2026-0142" }, { title: "Byrne estate distribution", id: "MAT-2026-0127" }, { title: "Northstar share transfer filing", id: "MAT-2026-0138" }] },
  ],
  timer: { running: false, startedAt: null, matterId: "MAT-2026-0142", narrative: "" },
  timeEntries: [
    { id: "TIME-601", date: "24 Aug", matterId: "MAT-2026-0142", person: "Niamh Kelly", narrative: "Review title replies and client instructions", hours: 0.8, rate: 320, amount: 256, status: "Posted", source: "Manual" },
    { id: "TIME-602", date: "24 Aug", matterId: "MAT-2026-0138", person: "Fionn Daly", narrative: "Disclosure index review and diligence notes", hours: 1.4, rate: 260, amount: 364, status: "Draft", source: "Activity suggestion" },
    { id: "TIME-603", date: "23 Aug", matterId: "MAT-2026-0119", person: "Ciarán Murphy", narrative: "Discovery index preparation", hours: 2.1, rate: 290, amount: 609, status: "Posted", source: "Manual" },
    { id: "TIME-604", date: "23 Aug", matterId: "MAT-2026-0127", person: "Eimear Walsh", narrative: "Executor call and valuation review", hours: 0.7, rate: 240, amount: 168, status: "Posted", source: "Timer" },
    { id: "TIME-605", date: "22 Aug", matterId: "MAT-2026-0142", person: "Niamh Kelly", narrative: "Contract review and requisition planning", hours: 1.6, rate: 320, amount: 512, status: "Billed", source: "Manual" },
  ],
  timeSuggestions: [
    { id: "SUG-301", matterId: "MAT-2026-0142", activity: "Edited Requisitions on Title — replies.docx", duration: 0.7, source: "Word activity", confidence: 96, status: "Suggested" },
    { id: "SUG-302", matterId: "MAT-2026-0138", activity: "Reviewed 3 Northstar email attachments", duration: 0.4, source: "Outlook activity", confidence: 91, status: "Suggested" },
    { id: "SUG-303", matterId: "MAT-2026-0119", activity: "Counsel conference notes", duration: 0.9, source: "Document activity", confidence: 87, status: "Suggested" },
  ],
  invoices: [
    { id: "INV-D-1042", matterId: "MAT-2026-0138", client: "Northstar Foods Ltd (Demo)", professional: 7400, outlays: 230, vat: 1775.1, total: 9405.1, status: "Partner approval", owner: "Fionn Daly", issued: "Draft", section150: "Current", billRef: "BOC-DEMO-1042" },
    { id: "INV-D-1041", matterId: "MAT-2026-0142", client: "Sample Client O'Rourke", professional: 3840, outlays: 430, vat: 981.1, total: 5251.1, status: "Draft", owner: "Niamh Kelly", issued: "Draft", section150: "Estimate reviewed", billRef: "BOC-DEMO-1041" },
    { id: "INV-1038", matterId: "MAT-2026-0119", client: "Sample Client Keane", professional: 6200, outlays: 840, vat: 1619.2, total: 8659.2, status: "Issued", owner: "Ciarán Murphy", issued: "18 Aug 2026", section150: "Update due", billRef: "BOC-DEMO-1038" },
  ],
  accounts: {
    balances: { client: 1248530, office: 486240, unreconciled: 2500, officeDebtors: 369500 },
    transactions: [
      { id: "TX-9008", ledger: "Client", date: "24 Aug", matterId: "MAT-2026-0142", description: "Purchase deposit received — synthetic", reference: "DEMO-SEPA-8841", debit: 0, credit: 48500, balance: 48500, matterBalance: 48500, status: "Matched" },
      { id: "TX-9007", ledger: "Client", date: "24 Aug", matterId: "MAT-2026-0127", description: "Estate property sale proceeds — synthetic", reference: "DEMO-SEPA-8839", debit: 0, credit: 420000, balance: 672400, matterBalance: 420000, status: "Matched" },
      { id: "TX-9006", ledger: "Client", date: "22 Aug", matterId: "MAT-2026-0138", description: "Unmatched receipt — proposed matter only — synthetic", reference: "DEMO-SEPA-8828", debit: 0, credit: 2500, balance: 1248530, status: "Review" },
      { id: "TX-9005", ledger: "Client", date: "22 Aug", matterId: "MAT-2026-0119", description: "Counsel outlay paid — synthetic", reference: "DEMO-PAY-2208", debit: 3200, credit: 0, balance: 18400, matterBalance: 18400, status: "Matched" },
      { id: "TX-8004", ledger: "Office", date: "24 Aug", matterId: "MAT-2026-0106", description: "Professional fees received — synthetic", reference: "INV-1036", debit: 0, credit: 2840, balance: 486240, status: "Posted" },
      { id: "TX-8003", ledger: "Office", date: "23 Aug", matterId: "MAT-2026-0119", description: "Counsel outlay recovered — synthetic", reference: "INV-1035", debit: 0, credit: 3200, balance: 483400, status: "Posted" },
    ],
    exceptions: [
      { id: "EXC-71", rule: "Three-month balancing", title: "Balancing statement review due in 6 days", detail: "Client account quarter ending 31 August · professional verification required", tone: "warning", status: "Open" },
      { id: "EXC-72", rule: "Dormant balances", title: "2 balances require Appendix 6 review", detail: "Synthetic balances with no movement for more than two years", tone: "danger", status: "Open" },
      { id: "EXC-73", rule: "Transfer control", title: "€4,860 transfer request is blocked", detail: "No linked written Bill of Costs reference", tone: "danger", status: "Blocked" },
      { id: "EXC-74", rule: "Bank reconciliation", title: "One €2,500 receipt is unmatched", detail: "Statement line has no confirmed matter reference", tone: "warning", status: "Review" },
    ],
    reconciliation: { statementBalance: 1248530, ledgerBalance: 1246030, difference: 2500, statementDate: "22 Aug 2026", matched: 42, pending: 1, status: "Difference found" },
    transferRequests: [
      { id: "TRF-118", matterId: "MAT-2026-0142", amount: 4860, billRef: "", requestedBy: "Niamh Kelly", status: "Blocked", reason: "Written Bill of Costs reference missing" },
      { id: "TRF-117", matterId: "MAT-2026-0119", amount: 3200, billRef: "BOC-DEMO-1035", requestedBy: "Ciarán Murphy", status: "Completed", reason: "Human-approved demo transfer" },
    ],
  },
  clients: [
    { id: "CL-201", name: "Sample Client O'Rourke", initials: "SO", type: "Individual", matters: ["MAT-2026-0142"], portal: "Active", lastActive: "Today, 08:51", email: "sample.orourke@example.invalid", phone: "+353 1 555 0101", risk: "Standard", balance: 48500, requests: [{ id: "REQ-1", title: "Upload proof of address", due: "Today", status: "Awaiting client" }, { id: "REQ-2", title: "Confirm €5,000 payment reference", due: "Today", status: "Awaiting client" }] },
    { id: "CL-202", name: "Northstar Foods Ltd (Demo)", initials: "NF", type: "Organisation", matters: ["MAT-2026-0138"], portal: "Active", lastActive: "Yesterday", email: "legal@northstar-demo.example.invalid", phone: "+353 1 555 0102", risk: "Enhanced review", balance: 250000, requests: [{ id: "REQ-3", title: "Approve disclosure schedule", due: "26 Aug", status: "Viewed" }] },
    { id: "CL-203", name: "Sample Estate of P. Byrne", initials: "PB", type: "Estate", matters: ["MAT-2026-0127"], portal: "Invited", lastActive: "24 Aug, 08:48", email: "executor@example.invalid", phone: "+353 1 555 0103", risk: "Standard", balance: 420000, requests: [{ id: "REQ-4", title: "Confirm beneficiary details", due: "28 Aug", status: "Draft" }] },
    { id: "CL-204", name: "Sample Client Keane", initials: "SK", type: "Individual", matters: ["MAT-2026-0119"], portal: "Active", lastActive: "20 Aug", email: "sample.keane@example.invalid", phone: "+353 1 555 0104", risk: "Standard", balance: 18400, requests: [{ id: "REQ-5", title: "Review discovery statement", due: "01 Sep", status: "Viewed" }] },
    { id: "CL-205", name: "Sample Client Gallagher", initials: "SG", type: "Individual", matters: ["MAT-2026-0106"], portal: "Not invited", lastActive: "18 Aug", email: "sample.gallagher@example.invalid", phone: "+353 1 555 0105", risk: "Standard", balance: 0, requests: [] },
  ],
  portalMessages: [
    { id: "PORT-1", clientId: "CL-201", side: "firm", time: "23 Aug, 17:06", text: "We are checking the updated figures and will send the remaining-item list tomorrow.", status: "Opened" },
    { id: "PORT-2", clientId: "CL-201", side: "client", time: "Today, 08:51", text: "The address document should be available later today. Is the proposed closing date still realistic?", status: "Received" },
    { id: "PORT-3", clientId: "CL-202", side: "firm", time: "Yesterday", text: "The second diligence tranche is ready for your review.", status: "Opened" },
  ],
  reports: {
    monthlyFees: [78000, 92000, 87000, 108000, 116000, 124500, 119000, 137800],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    practiceAreas: [
      { name: "Conveyancing", matters: 42, wip: 68420, billed: 232600, recovery: 91 },
      { name: "Corporate", matters: 19, wip: 52860, billed: 246300, recovery: 94 },
      { name: "Litigation", matters: 28, wip: 39480, billed: 154600, recovery: 83 },
      { name: "Probate", matters: 23, wip: 17400, billed: 132200, recovery: 88 },
      { name: "Employment", matters: 16, wip: 10100, billed: 96600, recovery: 90 },
    ],
    aged: [
      { label: "Current", value: 61, amount: 218400 },
      { label: "30–60 days", value: 23, amount: 84600 },
      { label: "61–90 days", value: 10, amount: 42600 },
      { label: "90+ days", value: 6, amount: 23900 },
    ],
  },
  pipeline: [
    { label: "Intake", value: 14, total: 128, tone: "slate" },
    { label: "Active work", value: 62, total: 128, tone: "navy" },
    { label: "Client action", value: 29, total: 128, tone: "amber" },
    { label: "Closing", value: 23, total: 128, tone: "teal" },
  ],
};

export const cloneSeedData = () => JSON.parse(JSON.stringify(seedData));
